.env:
  directory: ./
  filename: .env
  ignoreIfMalformed: true
  ignoreIfMissing: true
  systemProperties: true
  prefix: ""

kafka:
  topic:
    send-email:
      request: send-email-request
      reply: send-email-reply

logging:
  file:
    name: ./tmp/email-service.log
  pattern:
    file: '%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg traceID=%X{trace_id} %n'
  level:
    com:
      camdigikey:
        emailservice: DEBUG
    org:
      hibernate:
        type: trace

server:
  tomcat:
    accesslog:
      enabled: true
      rotate: false
      suffix: .log
      prefix: access-log
      directory: ./tmp
      pattern: common

management:
  endpoints:
    web:
      exposure:
        include:
          - prometheus

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/email-service}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}

  kafka:
    properties:
      schema.registry.url: ${SCHEMA_REGISTRY:http://localhost:8081}
    bootstrap-servers: ${BOOTSTRAP_SERVERS:localhost:9092}

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL:update}
  # mailgun
  mail:
    # smtp
    host: ${MAILGUN_HOST:abc}
    port: ${MAILGUN_PORT:0}
    username: ${MAILGUN_USERNAME:abc}
    password: ${MAILGUN_PASSWORD:abc}
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          from: ${MAILGUN_FROM:erenthewizard@gmail.com}
    default-encoding: UTF-8
    # api
    api-key: ${MAILGUN_API_KEY:abc}
    api-base-url: ${MAILGUN_API_BASE_URL:abc}
  #sendgrid
  sendgrid:
    api-key: ${SENDGRID_API_KEY:abc}
    properties:
      mail:
        from: ${SENDGRID_MAIL_FROM:abc}

mail:
  provider: ${MAIL_PROVIDER:mailgun}
  from:
    name: ${MAIL_FROM_NAME:abc}

retry:
  maxAttempts: 3
  retry.maxDelay: 100

